app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ApiOverview, name='api-overview'),

    # Product endpoints
    path('products/', views.product_list, name='product-list'),
    path('products/create/', views.product_create, name='product-create'),
    path('products/<int:pk>/update/', views.product_update, name='product-update'),
    path('products/<int:pk>/delete/', views.product_delete, name='product-delete'),

    # Category endpoints
    path('categories/', views.category_list, name='category-list'),
    path('categories/create/', views.category_create, name='category-create'),
    path('categories/<int:pk>/update/', views.category_update, name='category-update'),
    path('categories/<int:pk>/delete/', views.category_delete, name='category-delete'),
]

root/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from root import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('shop/', include('app.urls')),
                  path('', include('users.urls')),
                  path('social-auth/',
                       include('social_django.urls', namespace='social')),
                  path('api-auth/', include('rest_framework.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views
from users.views import (
    CustomerListView, CustomerDetailView,
    CustomerCreateView, CustomerUpdateView, CustomerDeleteView
)

app_name = 'users'

urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('register/', views.RegisterPage.as_view(), name='register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('customers/', CustomerListView.as_view(), name='customers'),
    path('customers/new/', CustomerCreateView.as_view(), name='customer_add'),
    path('customers/<slug:slug>/', CustomerDetailView.as_view(), name='customer_detail'),
    path('customers/<slug:slug>/update/', CustomerUpdateView.as_view(), name='customer_update'),
    path('customers/<slug:slug>/delete/', CustomerDeleteView.as_view(), name='customer_delete'),
    path('email-required/', views.email_required, name='email_required'),
    path('verifiy-email-done/', views.verify_email_done, name='verify_email_done'),
    path('verify-email-confirm/<uidb64>/<token>/', views.verify_email_confirm, name='verify_email_confirm'),
    path('export-data/', views.export_data, name='export_data')
]

users/models.py
import random
from django.contrib.auth.models import AbstractBaseUser
from django.db import models
from django.utils.text import slugify

from .managers import CustomUserManager


class Customer(AbstractBaseUser):
    username = None
    name = models.CharField(max_length=100, unique=True,null=False, blank=True)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=100, blank=True, null=True)
    billing_address = models.TextField(blank=True, null=True)
    password = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='avatars/', null=True, blank=True)
    slug = models.SlugField(unique=True, blank=True)
    VAT_Number = models.CharField(max_length=9, unique=True, blank=True)

    USERNAME_FIELD = 'name'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def save(self, *args, **kwargs):
        if not self.slug or self.slug.strip() == "":
            base_slug = slugify(self.name)
            slug = base_slug
            counter = 1
            while Customer.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            self.slug = slug

        if not self.VAT_Number:
            self.VAT_Number = str(random.randint(100000000, 999999999))

        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.name} {self.email} {self.VAT_Number}"

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.hashers import make_password
from django.core.exceptions import ValidationError
from django.forms import PasswordInput

from users.apps import UsersConfig
from users.models import Customer



class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=PasswordInput)



class RegisterModelForm(forms.ModelForm):
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = Customer
        fields = ('name','email', 'password', 'confirm_password')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and Customer.objects.filter(email=email.lower()).exists():
            raise forms.ValidationError(f'This {email} is already registered.')
        return email.lower()

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if Customer.objects.filter(name=name).exists():
            raise forms.ValidationError(f'Username "{name}" is already taken.')
        return name

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Passwords don't match.")
        return confirm_password

    def save(self, commit=True):
        user = super().save(commit=False)
        user.password = make_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

users/views.py
import csv
import json

import openpyxl
from django.contrib import messages
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import FormView
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from app.forms import CustomerForm
from users.forms import RegisterModelForm, LoginForm
from users.models import Customer
from users.tokens import account_activation_token


# Create your views here.


class CustomerListView(ListView):
    model = Customer
    template_name = 'app/customers.html'
    context_object_name = 'customers'

    def get_queryset(self):
        query = self.request.GET.get('q', '')
        if query:
            return Customer.objects.filter(name__icontains=query)
        return Customer.objects.all()


class CustomerDetailView(View):
    def get(self, request, slug):
        customer = get_object_or_404(Customer, slug=slug)
        return render(request, 'app/customer-details.html', {'customer': customer})


class CustomerCreateView(CreateView):
    model = Customer
    form_class = CustomerForm
    template_name = 'app/customer_add.html'
    success_url = reverse_lazy('users:customers')


class CustomerUpdateView(UpdateView):
    model = Customer
    form_class = CustomerForm
    template_name = 'app/customer_update.html'
    success_url = reverse_lazy('users:customers')

    def get_object(self, queryset=None):
        return get_object_or_404(Customer, name=self.kwargs.get('slug'))


class CustomerDeleteView(DeleteView):
    model = Customer
    template_name = 'app/customer_delete.html'
    success_url = reverse_lazy('users:customers')

    def get_object(self, queryset=None):
        return get_object_or_404(Customer, slug=self.kwargs.get('slug'))


def login_page(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, email=cd['email'], password=cd['password'])
            if user:
                if user.is_active:
                    login(request, user)
                    return redirect('app:index')
                else:
                    messages.add_message(
                        request,
                        messages.ERROR,
                        'Disabled account'
                    )
                    return render(request, 'users/login.html')
            else:
                messages.add_message(
                    request,
                    messages.ERROR,
                    'Username or Password invalid'
                )
                return render(request, 'users/login.html')

    return render(request, 'users/login.html', {'form': form})


class RegisterPage(FormView):
    template_name = 'users/register.html'
    form_class = RegisterModelForm
    success_url = reverse_lazy('users:verify_email_done')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_staff = True
        user.is_superuser = True
        user.is_active = False
        user.set_password(user.password)
        user.save()
        current_site = get_current_site(self.request)
        subject = "Verify Email"
        message = render_to_string('users/Email/verify_email_message.html', {
            'request': self.request,
            'user': user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': account_activation_token.make_token(user),
        })
        user.save()
        email = EmailMessage(
            subject, message, to=[user.email]
        )
        email.content_subtype = 'html'
        email.send()
        return super().form_valid(form)


def email_required(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        user = request.user

        if user.is_authenticated and not user.is_active:
            user.email = email
            user.save()
            return redirect('app:index')
    return render(request, 'Github/email-required.html')


def verify_email_done(request):
    return render(request, 'users/Email/verify_email_done.html')


def verify_email_confirm(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = Customer.objects.get(pk=uid)

    except(TypeError, ValueError, OverflowError, Customer.DoesNotExist):
        user = None
    if user and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        messages.success(request, 'Your email has been verified.')
        return redirect('app:index')
    else:
        messages.warning(request, 'The link is invalid.')
    return render(request, 'users/email/verify_email_confirm.html')



class LogoutView(View):
    def get(self, request):
        return render(request, 'users/logout.html')

    def post(self, request):
        logout(request)
        messages.success(request, "Succesfully logout")
        return redirect('app:index')


def export_data(request):
    format = request.GET.get('format')
    if format == 'csv':
        meta = Customer._meta
        field_names = [field.name for field in meta.fields]
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="customer_list.csv'
        writer = csv.writer(response)
        writer.writerow(field_names)
        for obj in Customer.objects.all():
            row = writer.writerow([getattr(obj, field) for field in field_names])
            return response

    elif format == 'json':
        response = HttpResponse(content_type='application/json')
        data = list(Customer.objects.all().values_list('id', 'name', 'email', 'phone', 'billing_address', 'password',
                                                       'created_at', 'image', 'slug', 'VAT_Number'))
        response.write(json.dumps(data, indent=4, default=str))
        response['Content-Disposition'] = 'attachment; filename="customer.json"'
        return response

    elif format == 'xlsx':
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = 'Customers List'

        colums = ['id', 'name', 'email', 'phone', 'billing_address', 'password', 'created_at', 'image', 'slug',
                  'VAT_Number']
        fields = ['id', 'name', 'email', 'phone', 'billing_address', 'password', 'created_at', 'image', 'slug',
                  'VAT_Number']

        for col_num, column_title in enumerate(colums, 1):
            ws.cell(row=1, column=col_num, value=column_title)

        customers = Customer.objects.all().values_list(*fields)

        for row_num, row_data in enumerate(customers, 2):
            for col_num, cell_value in enumerate(row_data, 1):
                if hasattr(cell_value, 'isoformat'):
                    cell_value = cell_value.isoformat()
                elif hasattr(cell_value, 'url'):
                    cell_value = cell_value.url
                ws.cell(row=row_num, column=col_num, value=cell_value)

        response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
        response['Content-Disposition'] = 'attachment; filename="customer.xlsx"'
        wb.save(response)
        return response

    else:
        response = HttpResponse(status=404)
        response.content = 'Bad request'
        return response

def home(request):
    if request.device_type == "Mobile":
        # return render(request, "mobile/home.html")     Mobile Telefon uchun html yaratiladi. Tez kunda!!!
        pass
    else:
        return render(request, "app/index.html")

users/templates/users/login.html
{% extends 'users/base/base.html' %}
{% load static %}

{% block title %} Login Page{% endblock %}

{% block login_content %}
    <main class="main" id="top">
        <div class="container-fluid">
            <div class="row min-vh-100 flex-center g-0">
                <div class="col-lg-8 col-xxl-5 py-3 position-relative"><img class="bg-auth-circle-shape"
                                                                            src="{% static 'app/assets/img/icons/spot-illustrations/bg-shape.png' %}"
                                                                            alt="" width="250"><img
                        class="bg-auth-circle-shape-2"
                        src="{% static 'app/assets/img/icons/spot-illustrations/shape-1.png' %}"
                        alt=""
                        width="150">
                    <div class="card overflow-hidden z-index-1">
                        <div class="card-body p-0">
                            <div class="row g-0 h-100">
                                <div class="col-md-5 text-center bg-card-gradient">
                                    <div class="position-relative p-4 pt-md-5 pb-md-7 light">
                                        <div class="bg-holder bg-auth-card-shape"
                                             style="background-image:url({% static 'app/assets/img/icons/spot-illustrations/half-circle.png' %});">
                                        </div>
                                        <!--/.bg-holder-->

                                        <div class="z-index-1 position-relative"><a
                                                class="link-light mb-4 font-sans-serif fs-4 d-inline-block fw-bolder"
                                                href="{% url 'app:index' %}">falcon</a>
                                            <p class="opacity-75 text-white">With the power of Falcon, you can now focus
                                                only on functionaries for your digital products, while leaving the UI
                                                design
                                                on us!</p>
                                        </div>
                                    </div>
                                    <div class="mt-3 mb-4 mt-md-4 mb-md-5 light">
                                        <p class="text-white">Don't have an account?<br><a
                                                class="text-decoration-underline link-light"
                                                href="{% url 'users:register' %}">Get started!</a>
                                        </p>
                                        <p class="mb-0 mt-4 mt-md-5 fs--1 fw-semi-bold text-white opacity-75">Read our
                                            <a
                                                    class="text-decoration-underline text-white" href="#!">terms</a> and
                                            <a
                                                    class="text-decoration-underline text-white"
                                                    href="#!">conditions </a></p>
                                    </div>
                                </div>
                                <div class="col-md-7 d-flex flex-center">
                                    <div class="p-4 p-md-5 flex-grow-1">
                                        <div>
                                            {% if messages %}
                                                <ul class="messages">
                                                    {% for message in messages %}
                                                        <li style="color:red;" {% if message.tags %}
                                                            class="{{ message.tags }}"{% endif %}>{{ message }}
                                                        </li>
                                                    {% endfor %}
                                                </ul>
                                            {% endif %}
                                            {% if form.errors %}
                                                <div class="alert alert-warning alert-dismissible fade show"
                                                     role="alert">
                                                    <p class="m-0">{{ form.errors }}</p>
                                                    <button type="button"
                                                            class="btn-close"
                                                            data-bs-dismiss="alert"
                                                            aria-label="Close">
                                                    </button>
                                                </div>
                                            {% endif %}
                                        </div>
                                        <div class="row flex-between-center">
                                            <div class="col-auto">
                                                <h3>Account Login</h3>
                                            </div>
                                        </div>
                                        <form method="post" action="{% url 'users:login' %}">
                                            {% csrf_token %}
                                            <div class="mb-3">
                                                <label class="form-label" for="card-email">Email address</label>
                                                <input class="form-control" name="email" id="card-email" type="email"/>
                                            </div>
                                            <div class="mb-3">
                                                <div class="d-flex justify-content-between">
                                                    <label class="form-label" for="card-password">Password</label>
                                                </div>
                                                <input class="form-control" name="password" id="card-password"
                                                       type="password"/>
                                            </div>
                                            <div class="row flex-between-center">
                                                <div class="col-auto">
                                                    <div class="form-check mb-0">
                                                        <input class="form-check-input" type="checkbox"
                                                               id="card-checkbox"
                                                               checked="checked"/>
                                                        <label class="form-check-label mb-0" for="card-checkbox">Remember
                                                            me</label>
                                                    </div>
                                                </div>
                                                <div class="col-auto"><a class="fs--1"
                                                                         href="../../../pages/authentication/card/forgot-password.html">Forgot
                                                    Password?</a></div>
                                            </div>
                                            <div class="mb-3">
                                                <button class="btn btn-primary d-block w-100 mt-3" type="submit"
                                                        name="submit">Log in
                                                </button>
                                            </div>
                                        </form>
                                        <div class="position-relative mt-4">
                                            <hr class="bg-300"/>
                                            <div class="divider-content-center">or log in with</div>
                                        </div>
                                        <div class="row g-2 mt-2">
                                            <div class="col-sm-6">
                                                <a
                                                        class="btn btn-outline-google-plus btn-sm d-block w-100"
                                                        href="{% url 'social:begin' 'google-oauth2' %}">
                                                    <span
                                                            class="fab fa-google-plus-g me-2"
                                                            data-fa-transform="grow-8">

                                                    </span>
                                                    google
                                                </a>
                                            </div>
                                            <div class="col-sm-6"><a
                                                    class="btn btn-outline-facebook btn-sm d-block w-100"
                                                    href="{% url 'social:begin' 'github' %}"><span class="fab fa-github-square me-2"
                                                                   data-fa-transform="grow-8"></span>
                                                github</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}